version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "github_actions"
      - "no_ci_cd_run"
  - package-ecosystem: "docker"
    directory: "/base/.devcontainer"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
