---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "github_actions"
      - "no_ci_cd_run"
    commit-message:
      prefix: "ci"
    groups:
      patch-minor-dependencies:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/base/.devcontainer"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
    commit-message:
      prefix: "build"
    groups:
      patch-minor-dependencies:
        update-types:
          - "minor"
          - "patch"
