FROM mcr.microsoft.com/vscode/devcontainers/base@sha256:800ed0a5e8679cf1bd2a1ec1ef01d35cc497d6fda21ed8811b04fb9f938def6e
COPY --chown=vscode:vscode settings.xml "/home/vscode/.m2/settings.xml"
USER vscode
