name: Generate Ansible Dev Container Image
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 20 * *'
  push:
    branches:
      - 'master'
    paths:
      - 'ansible/**'
      - 'base/**'
permissions:
  contents: read
  packages: write
jobs:
  devcontainer:
    uses: ./.github/workflows/generate-devcontainer-image.yaml
    with:
      devcontainername: "ansible"
