name: Generate Aws Terraform Dev Container Image
on:
  workflow_dispatch:  
  schedule:
    - cron: '0 0 20 * *'
  push:
    branches:
      - 'master'
permissions:
  contents: read
  packages: write
jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/generate-devcontainer-image.yaml
        with:
          devcontainername: "aws-terraform"