name: Generate Aws Terraform Dev Container Image
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 20 * *"
  push:
    branches:
      - "master"
    paths:
      - "aws-terraform/**"
  workflow_run:
    workflows: [Generate Base Dev Container Image]
    types:
      - completed
permissions:
  contents: read
  packages: write
jobs:
  devcontainer:
    uses: ./.github/workflows/generate-devcontainer-image.yaml
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    with:
      devcontainername: "aws-terraform"
