# This name is used to trigger other workflows
name: Generate Base Dev Container Image
on:
  workflow_dispatch:
  # Runs the day before other scheduled tasks
  schedule:
    - cron: "0 0 19 * *"
  push:
    branches:
      - "master"
    paths:
      - "base/**"
env:
  DEBIAN_VERSION: "debian-11"
  GITLEAKS_VERSION: "8.15.0"
  GIT_MKVER_VERSION: "1.2.2"
  NODE_VERSION: "node_16.x"
  DELTA_VERSION: "0.14.0"
  ASDF_VERSION: "0.10.0"
permissions:
  contents: read
  packages: write
jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - uses: actions/setup-node@v3.5.0
        with:
          node-version: "16"

      - run: |
          set -e

          IMAGE_REPOSITORY="ghcr.io/${{ github.repository_owner }}/devcontainers/base:latest"

          # Enable buildkit, set output to plain text for logging
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain

          # Do the build - update
          docker build --build-arg DEBIAN_VERSION=$DEBIAN_VERSION \
                       --build-arg GITLEAKS_VERSION=$GITLEAKS_VERSION \
                       --build-arg GIT_MKVER_VERSION=$GIT_MKVER_VERSION \
                       --build-arg NODE_VERSION=$NODE_VERSION \
                       --build-arg DELTA_VERSION=$DELTA_VERSION \
                       --build-arg ASDF_VERSION=$ASDF_VERSION \
                       --progress=plain \
                       --tag $IMAGE_REPOSITORY \
                       base/.devcontainer

          # Push image to GitHub Container Registry
          echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push "${IMAGE_REPOSITORY}"
