# This name is used to trigger other workflows
---
name: Generate Base Dev Container Image
on:
  workflow_dispatch:
  # Runs the day before other scheduled tasks
  schedule:
    - cron: "0 0 19 * *"
  push:
    branches:
      - "master"
    paths:
      - "base/**"
permissions:
  contents: read
  packages: write
jobs:
  devcontainer:
    permissions:
      contents: read
      packages: write
    uses: aps831/workflows/.github/workflows/generate-devcontainer-image.yaml@master
    with:
      devcontainer-name: "base"
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
