# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Bitbucket Mirror
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
permissions:
  contents: read
  issues: read
  pull-requests: read
jobs:
  mirror:
    uses: aps831/workflows/.github/workflows/bitbucket-mirror.yaml@master
    with:
      repositoryname: devcontainers
    secrets:
      BITBUCKET_SSH_PRIVATE_KEY: ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}
