name: Generate Dev Container Image
on:
  workflow_call:
    inputs:
      devcontainername:
        required: true
        type: string
permissions:
  contents: read
  packages: write
jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: |
          set -e

          FOLDER_WITH_DOT_DEVCONTAINER=${{ inputs.devcontainername }}
          IMAGE_NAME="devcontainers/${{ inputs.devcontainername }}"
          IMAGE_REPOSITORY="$(echo "ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:latest" | tr '[:upper:]' '[:lower:]')"

          # Enable buildkit, set output to plain text for logging
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain

          # Do the build - update
          npm install -g "@vscode/dev-container-cli"
          devcontainer build --image-name "${IMAGE_REPOSITORY}" "${FOLDER_WITH_DOT_DEVCONTAINER}"

          # Push image to GitHub Container Registry
          echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push "${IMAGE_REPOSITORY}"
