name: Generate Go Dev Container Image
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 20 * *'
  push:
    branches:
      - 'master'
    paths:
      - 'go/**'
  workflow_run:
    workflows: [Generate Base Dev Container Image]
    types:
      - completed
permissions:
  contents: read
  packages: write
jobs:
  devcontainer:
    uses: ./.github/workflows/generate-devcontainer-image.yaml
    with:
      devcontainername: "go"
