name: Generate Java 8 Maven 3 Dev Container Image
on:
  workflow_dispatch:  
  schedule:
    - cron: '0 0 20 * *'
  push:
    branches:
      - 'master'
permissions:
  contents: read
  packages: write
jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          set -e
          
          FOLDER_WITH_DOT_DEVCONTAINER="java8-maven3"
          IMAGE_NAME="devcontainers/java8-maven3"
          IMAGE_REPOSITORY="$(echo "ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:latest" | tr '[:upper:]' '[:lower:]')"

          # Enable buildkit, set output to plain text for logging
          export DOCKER_BUILDKIT=1
          export BUILDKIT_PROGRESS=plain

          # Do the build - update
          npm install -g "@vscode/dev-container-cli"
          devcontainer build --no-cache --image-name "${IMAGE_REPOSITORY}" "${FOLDER_WITH_DOT_DEVCONTAINER}"

          # Push image to GitHub Container Registry
          echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push "${IMAGE_REPOSITORY}"
