name: Generate Java 8 Maven 3 Dev Container Image
on:
  workflow_dispatch:  
  schedule:
    - cron: '0 0 20 * *'
  push:
    branches:
      - 'master'
permissions:
  contents: read
  packages: write
jobs:
  devcontainer:
    uses: ./.github/workflows/generate-devcontainer-image.yaml
    with:
      devcontainername: "java8-maven3"