---
name: Generate Java Maven Dev Container Image
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 20 * *"
  push:
    branches:
      - "master"
    paths:
      - "java-maven/**"
  workflow_run:
    workflows: [Generate Base Dev Container Image]
    types:
      - completed
permissions:
  contents: read
  packages: write
jobs:
  devcontainer:
    permissions:
      contents: read
      packages: write
    uses: aps831/workflows/.github/workflows/generate-devcontainer-image.yaml@master
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    with:
      devcontainer-name: "java-maven"
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
