---
name: Permissions Advisor (Run)
permissions:
  actions: read
on:
  workflow_dispatch:
    inputs:
      name:
        description: "The name of the workflow file to analyze"
        required: true
        type: string
      runs:
        description: "How many last runs to analyze"
        required: false
        type: number
        default: 10
jobs:
  advisor:
    uses: aps831/workflows/.github/workflows/permissions-advisor.yaml@master
    with:
      name: ${{ inputs.name }}
      runs: ${{ fromJSON(inputs.runs) }} # 🙈
