name: Semgrep Static Analysis
on:
  workflow_dispatch:
  pull_request: {}
  schedule:
    - cron: 0 4 18 * *
jobs:
  semgrep:
    uses: aps831/workflows/.github/workflows/semgrep.yaml@master
permissions:
  contents: read
  issues: read
  pull-requests: read
